server:
  port: 9091
  
spring:
  application: 
    name: allianz-product-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:product_db
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  resources: 
      chain: 
        enabled: true
  main: 
    allow-bean-definition-overriding: true
        
jwt:
  client: 
    secret : RdGllrHtJ8uX14xRDXvEtp639OsZjVBwMbZiy
    
logging:
  level: 
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
  
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://allianz-eureka-server.cfapps.io/eureka}
  instance:
    preferIpAddress: true
        