server:
  port: 9090
  
 
eureka:
  instance:
    appname: documentation-application
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:https://allianz-eureka-server.cfapps.io/eureka}
      
swagger: 
  config: 
    refreshrate: 5000