server:
  port: 8085
jwt:
  client:
    secret: RdGllrHtJ8uX14xRDXvEtp639OsZjVBwMbZiy
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:auth
    username: sa
    password:
  main: 
    allow-bean-definition-overriding: true
  application:
    name: allianz-auth-service
    
logging:
  level: 
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
  
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true